### ISSUE TITLE
Anything??

### ISSUE THREAD

**Issue by GoodFaut** [rana-mc/rana-mc#2]
anything there??

**Comment by redzumi** [comment]
Hi, @GoodFaut 

Yep, was paused, but now project under development
As goal - first release in Q2

Some details in design:

![ServerCreate page](https://user-images.githubusercontent.com/20846670/165471829-c8da2e0d-f2c3-42e0-bc43-97789447d2fd.jpg)
![Servers page](https://user-images.githubusercontent.com/20846670/165471821-0fa93d45-63af-47b7-84e5-22cae437c058.jpg)
![Mods page](https://user-images.githubusercontent.com/20846670/165471832-dfb2bc40-6c4e-4bab-b471-868745dd09b5.jpg)
